### PR TITLE
chore: add stale config

### PR DESCRIPTION
**Pull request by agraebe**
Adding stale config [from template](https://github.com/blockstack/.github/blob/master/.github/stale.yml)

### CODE REVIEW

**Comment by agraebe** [comment]
> we should consider putting tighter bounds for stale PRs?

I was thinking about that as well! Do you think that should be updated in the template or just isolated for our few repos? would we consider 90 days to be better?

**Comment by agraebe** [comment]
> > we should consider putting tighter bounds for stale PRs?
> 
> I was thinking about that as well! Do you think that should be updated in the template or just isolated for our few repos? would we consider 90 days to be better?

updated it individually now

**Comment by CharlieC3** [comment]
@agraebe Just a heads up, it seems the merge of this PR created a new release because it contained a commit with the `fix` type in the message. [You can find info on conventional commits and what commit message "types" trigger a release here](https://www.conventionalcommits.org/en/v1.0.0/#summary). Not a problem, just thought you might want to know about it for future reference.

**Comment by agraebe** [comment]
Oh, thanks for pointing this out!

**Pull request merged**
