### PR TITLE
Feat: JsonRcp provider, #82

### LINKED ISSUE #82: Implement JSONRcp provider
There is a skelecton for a json rcp provider: https://github.com/blockstack/clarity-js-sdk/blob/master/packages/clarity/src/providers/jsonRpc/index.ts

stacks-transaction-js could fulfill most of the required methods.

What is the plan here? Does it make sense?

### PR DESCRIPTION
**Pull request by friedger**
This is the start of a proposal for the implementation of the JsonRcp provider.

Use the same client for test in VM as well as mocknet or testnet

Fixes #82

### CODE REVIEW

**Comment by lgalabru** [comment]
This PR would be a game changer in terms of DX, what's the latest @friedger?

**Comment by friedger** [comment]
@lgalabru Discussion with @agraebe is going on to clarify what the final goal is for #82. It was mentioned that there should be support for Connect, however, I don't really understand. Maybe we need to change the API of the Provider interface. Until the API is settled on, I do not plan to push this further.

**Comment by agraebe** [comment]
@lgalabru agree with your assessment :) would love @hstove's input, even if it's just a "let's move forward and review later"

**Review by hstove — CHANGES_REQUESTED** [review]
Thanks @friedger ! In addition to what I mentioned, you have a lot of `console.log`s that should be removed.

**Pull request closed without merging**
