### PR TITLE
fix windows unit test

### PR DESCRIPTION
**Pull request by nervehammer**
removed finally block as the directory is not removed currently and if we actually try to remove directory, it throws an `error: resource busy` in windows

### CODE REVIEW

**Comment by zone117x** [comment]
Thanks for working on this. This seems indicative of some other underlying issue -- like some child process staying open. I'm running into more `clarity-cli` unit test errors than just this one when running on my own Windows machine, which seem related to this. 

On Windows, the `clarity-cli` unit tests seem to be triggering the unit tests in an unrelated project then proceed to fail.

**Comment by nervehammer** [comment]
@zone117x have you tried to remove `.yo-test` directory under clarity-cli/test ?

**Comment by zone117x** [comment]
@nervehammer Good call, that seems to fix it.

That temp `.yo-test` dir was never meant to be placed within a src dir (including `test/**/*.ts`), and so its picked up in subsequent tests.

Could you modify this PR with a couple changes?
1. Move the `new.test.ts` file up a directory -- fixes that temp dir issue, and no need for it to be in a `commands` subdir.
2. Change that finally statement to something like a try/catch so other platforms still get cleaned
```ts
try {
  fs.removeSync(testingDir);
} catch (error) {
  console.debug(`Unexpected error cleaning temp dir: ${testingDir}`);
}
```

Thanks for the help on this.

**Comment by nervehammer** [comment]
@zone117x done requested changes.

**Pull request merged**
